### ISSUE TITLE
cannot find module 'Bootstrap.Navbar'

### ISSUE THREAD

**Issue by jshickey** [rundis/elm-bootstrap.info#3]
Tried to follow the directions to run after cloning and I'm getting:

ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
I cannot find module 'Bootstrap.Navbar'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

**Comment by rundis** [comment]
Just tested in in an empty dir and worked fine.

1) Did you first clone elm-bootstrap ?
2) Did you clone elm-bootstrap.info as a sub-directory of elm-bootstrap ?

* elm-bootstrap
    * elm-bootstrap.info
        * src
        * ...
        * elm-package.json
    * src
    * elm-package.json

**Comment by rundis** [comment]
@jshickey Have you managed to get it up and running ?

**Comment by jshickey** [comment]
Sorry about my speed-reading the directions. I missed the cd into elm-bootstrap before cloning elm-bootstrap.info. The directions are fine - it works.

**Comment by rundis** [comment]
Cool
