### ISSUE TITLE
Weird build failure

### ISSUE THREAD

**Issue by slimey** [rundis/elm-bootstrap.info#5]
With a fresh clone, I get: `I cannot find module 'Bootstrap.Form.Fieldset'. Module 'Page.Form' is trying to import it.` I'm afraid I don't know why - it's there in `elm-stuff/packages/rundis/elm-bootstrap/1.1.0/src/Bootstrap/Form/Fieldset.elm` - and the rest of it seems fine. Any ideas?

**Comment by rundis** [comment]
Plese check the readme instructions again. You need to download elm-bootstrap.info as a subdir of elm-bootstrap.

**Comment by rundis** [comment]
Thats the second issue on this, so I guess I need to make the instructions clearer.

**Comment by rundis** [comment]
Updated/clarified setup instructions.
